name: ${COMPOSE_PROJECT_NAME:-nntmux-ci}

services:
  laravel.test:
    build:
      context: ../docker/8.5
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: nntmux-ci/php85
    environment:
      APP_ENV: testing
      COMPOSER_AUTH: '${COMPOSER_AUTH:-}'
      WWWUSER: '${WWWUSER}'
    volumes:
      - '..:/var/www/html'

  mariadb:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: cbp_integration
      MARIADB_USER: sail
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    healthcheck:
      test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
      interval: 2s
      timeout: 5s
      retries: 30
